//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosDelivery
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DELIVERYEntities : DbContext
    {
        public DB_DELIVERYEntities()
            : base("name=DB_DELIVERYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAB_FACTURA> CAB_FACTURA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual DbSet<ESTADO_ENVIO> ESTADO_ENVIO { get; set; }
        public virtual DbSet<ESTADO_PAGO> ESTADO_PAGO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO_CATEGORIA> PRODUCTO_CATEGORIA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
